### ISSUE TITLE
`Labeller` step always fails on PRs from forks

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/VersionVigilante.jl#26]
The `Labeller` step will always fail on PRs made from forks. See e.g. https://github.com/bcbi/VersionVigilante.jl/commit/4da7d1ad2750fdfe6778ccd49fcca71443891758/checks?check_suite_id=330591815

This is because GitHub Actions on PRs from forks do not have write permissions on the base repo, for security reasons. For more details, see this: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token

Is there a way to automatically skip the`Labeller` step if the PR is from a fork?

I always want to run the`VersionVigilante.main` step on all PRs, whether they are from the base repo or a fork. I only want to skip the `Labeller` step.

cc: @SaschaMann

**Comment by SaschaMann** [comment]
Adding `continue-on-error: true` to the labeller step is the easiest way, I think. I really hope they add more fine-grained permissions at some point...

**Comment by DilumAluthge** [comment]
> Adding `continue-on-error: true` to the labeller step is the easiest way, I think. I really hope they add more fine-grained permissions at some point...

It looks like that works. Thanks!

**Comment by DilumAluthge** [comment]
Fixed by #27
