### ISSUE TITLE
Remove the `needs version bump` label once VersionVigilante is passing?

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/VersionVigilante.jl#30]
Current behavior: After the `needs version bump` label has been added, it is never removed, even once VersionVigilante is passing.

Desired behavior: Once VersionVigilante is passing, it should try to remove the `needs version bump` label from the PR.

@SaschaMann Do you think you could help me with this?

**Comment by SaschaMann** [comment]
Untested: `github.issues.removeLabel({...context.issue, 'needs version bump'})` in a step that only runs when the VersionVigilante step passes (https://octokit.github.io/rest.js/#octokit-routes-issues-remove-label)

I have to check if/how we can check the success status of a specific step.
