### ISSUE TITLE
Add a way to ignore files

### ISSUE THREAD

**Issue by Octogonapus** [bcbi/VersionVigilante.jl#65]
We like VersionVigilante, but sometimes we make changes to files that have nothing to do with the version number of a package and get annoyed at VersionVigilante failing because it wants a version bump. What about adding a feature where you can configure file paths (e.g., `.github/*`) that are ignored? An ignored file would not require a version bump.

I am happy to work on this if a PR would be accepted and if someone points me in the right direction.

**Comment by DilumAluthge** [comment]
This is actually pretty easy to do. There is no modification needed to CompatHelper itself. You just make some edits to the `.github/workflows/CompatHelper.yml` file.

@ericphanson Could you post some examples of how to do this?

**Comment by ericphanson** [comment]
Yeah, you can just add a `paths-ignore` line to the trigger, like in https://github.com/ericphanson/GuessworkQuantumSideInfo.jl/blob/61997fa4d7b8dc03b9fbf135270454c58459f447/.github/workflows/ci.yml#L9

**Comment by DilumAluthge** [comment]
I'm going to close this as I think it's solved now.
